// Automatically generated by astro-icon
// d522661cbda1d13de6336b0cbbd22fd0229bf9788df63ec44471f340e66d8a0d

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "tabler:bulb"
		| "tabler:alert-triangle"
		| "tabler:flame"
		| "tabler:info-circle"
		| "tabler:arrow-narrow-left"
		| "tabler:arrow-narrow-right"
		| "tabler:menu-2"
		| "tabler:x"
		| "tabler:chevron-down"
		| "tabler:category"
		| "tabler:calendar-event"
		| "gridicons/quote"
		| "mynaui/arrow-long-right"
		| "socials/basil-instagram-solid"
		| "socials/mdi-facebook"
		| "socials/mdi-twitter"
		| "socials/mdi-youtube";
}